// <auto-generated />
using System;
using DCVLicenseServer.EntityFrameworkCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DCVLicenseServer.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20190620060320_addapilicense")]
    partial class addapilicense
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DCVLicenseServer.Core.APILicenses.APILicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("APIList");

                    b.Property<string>("AppId")
                        .IsRequired();

                    b.Property<string>("Claimer")
                        .IsRequired();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUserIp");

                    b.Property<int>("EndTime");

                    b.Property<string>("FileContent");

                    b.Property<string>("FileName");

                    b.Property<string>("Project")
                        .IsRequired();

                    b.Property<string>("Remark");

                    b.Property<int>("StartTime");

                    b.Property<int>("TotalTime");

                    b.Property<string>("ZipFilePath");

                    b.HasKey("Id");

                    b.ToTable("APILicenses");
                });

            modelBuilder.Entity("DCVLicenseServer.Core.ProductLicense.ProductLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Claimer")
                        .IsRequired();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUserIp");

                    b.Property<int>("DeviceNumber");

                    b.Property<int>("EndTime");

                    b.Property<string>("MachineCode")
                        .IsRequired();

                    b.Property<string>("Project")
                        .IsRequired();

                    b.Property<string>("Remark");

                    b.Property<int>("StartTime");

                    b.Property<string>("SystemFileContent");

                    b.Property<string>("SystemFileName");

                    b.Property<string>("TimeFileContent");

                    b.Property<string>("TimeFileName");

                    b.Property<int>("TotalTime");

                    b.Property<string>("ZipFilePath");

                    b.HasKey("Id");

                    b.ToTable("ProductLicenses");
                });

            modelBuilder.Entity("DCVLicenseServer.Core.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
